<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
/**
 * This file is automatically generated from Chatwing API
 * @author chatwing 
 */
return array(
    'app/float_ui/list' => array(
        'type' => 'get',
        'auth' => true
    ),
    'chatbox/read' => array(
        'type' => 'get',
        'auth' => true
    )
);